stages:
  # - build
  - validate

# build-dotnet:
#   stage: build
#   image: mcr.microsoft.com/dotnet/sdk:7.0
#   script:
#     - cd XmiToCode
#     - dotnet build

# validate-xmi:
#   stage: validate
#   image: mcr.microsoft.com/dotnet/sdk:7.0
#   script:
#     - cd XmiToCode
#     - dotnet run validate

test-xmi:
  stage: validate
  image: mcr.microsoft.com/dotnet/sdk:7.0
  variables:
   XMI_PATH: ${CI_PROJECT_DIR}/cleaned_23.xmi
  script:
    - cd Eulynx.Validation
    - 'dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml
