stages:
  - test
  - validate
  # - generate
  # - compile
  - report

build-and-test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:7.0
  variables:
   XMI_PATH: ${CI_PROJECT_DIR}/cleaned_22.xmi
  script:
    - cd XmiToCode.Test
    - dotnet test

parse-classes:
  stage: validate
  image: mcr.microsoft.com/dotnet/sdk:7.0
  variables:
   XMI_PATH: ${CI_PROJECT_DIR}/cleaned_22.xmi
  script:
    - cd Eulynx.Validation
    - 'dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-parse-classes-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose" --filter "TestCategory=parse-classes"'
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml

generate-c:
  stage: validate
  image: mcr.microsoft.com/dotnet/sdk:7.0
  allow_failure: true
  variables:
   XMI_PATH: ${CI_PROJECT_DIR}/cleaned_22.xmi
  script:
    - set +e
    - cd Eulynx.Validation
    - 'dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-generate-c-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose" --filter "TestCategory=generate-c" || EXIT_CODE=$?'
    - cd bin/Eulynx/C
    - apt update && apt install -y --no-install-recommends clang-format
    - find . -iname '*.h' -o -iname '*.c' | xargs clang-format -style=LLVM -i
    - exit $EXIT_CODE
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
      - ./Eulynx.Validation/bin/Debug/Eulynx/C
    reports:
      junit:
        - ./**/*test-result.xml

generate-rust:
  stage: validate
  image: mcr.microsoft.com/dotnet/sdk:7.0
  allow_failure: true
  variables:
   XMI_PATH: ${CI_PROJECT_DIR}/cleaned_22.xmi
  script:
    - cd Eulynx.Validation
    - 'dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-generate-rust-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose" --filter "TestCategory=generate-rust"'
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml

generate-csharp:
  stage: validate
  image: mcr.microsoft.com/dotnet/sdk:7.0
  allow_failure: true
  variables:
   XMI_PATH: ${CI_PROJECT_DIR}/cleaned_22.xmi
  script:
    - cd Eulynx.Validation
    - 'dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-generate-csharp-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose" --filter "TestCategory=generate-csharp"'
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml

generate-klee:
  stage: validate
  image: mcr.microsoft.com/dotnet/sdk:7.0
  allow_failure: true
  variables:
   XMI_PATH: ${CI_PROJECT_DIR}/cleaned_22.xmi
  script:
    - set +e
    - cd Eulynx.Validation
    - 'dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-generate-klee-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose" --filter "TestCategory=generate-klee" || EXIT_CODE=$?'
    - cd bin/Eulynx/Klee
    - apt update && apt install -y --no-install-recommends clang-format
    - find . -iname '*.h' -o -iname '*.c' | xargs clang-format -style=LLVM -i
    - exit $EXIT_CODE
  artifacts:
    when: always
    paths:
      - ./Eulynx.Validation/bin/Debug/Klee
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml

compile-c:
  stage: validate
  needs:
    - job: generate-c
      artifacts: true
  image: mcr.microsoft.com/dotnet/sdk:7.0
  variables:
   XMI_PATH: ${CI_PROJECT_DIR}/cleaned_22.xmi
  script:
    - rm ./artifacts/*.xml
    - apt-get update && apt-get install --no-install-recommends -y build-essential
    - cd Eulynx.Validation
    - 'dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-compile-c-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose" --filter "TestCategory=compile-c"'
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml

compile-klee:
  stage: validate
  needs:
    - job: generate-klee
      artifacts: true
  image: klee/klee:3.0
  variables:
   XMI_PATH: ${CI_PROJECT_DIR}/cleaned_22.xmi
  script:
    - rm ./artifacts/*.xml
    - sudo chown -R klee:klee Eulynx.Validation/bin/Debug/Klee
    - sudo apt-get update && sudo apt-get install --no-install-recommends -y dotnet-sdk-7.0
    - cd Eulynx.Validation
    - 'dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-compile-klee-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose" --filter "TestCategory=compile-klee"'
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml

test-report:
  stage: report
  image: node:18
  rules:
    - when: always
  script:
   - cp artifacts/*.xml testreport/app/\(default\)/dashboard/
   - cd testreport
   - npm i
   - npm run build
  artifacts:
    paths:
      - ./testreport/out
