stages:
  - build
  - validate

build-dotnet:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:7.0
  script:
    - cd XmiToCode
    - dotnet build

validate-xmi:
  stage: validate
  image: mcr.microsoft.com/dotnet/sdk:7.0
  script:
    - cd XmiToCode
    - dotnet run validate
