/**
 * @fileoverview gRPC-Web generated client stub for eulynx.point
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.3
// source: subsystem_point.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as subsystem_point_pb from './subsystem_point_pb';


export class SubsystemPointClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorConnectWeb = new grpcWeb.MethodDescriptor(
    '/eulynx.point.SubsystemPoint/ConnectWeb',
    grpcWeb.MethodType.SERVER_STREAMING,
    subsystem_point_pb.Nothing,
    subsystem_point_pb.State,
    (request: subsystem_point_pb.Nothing) => {
      return request.serializeBinary();
    },
    subsystem_point_pb.State.deserializeBinary
  );

  connectWeb(
    request: subsystem_point_pb.Nothing,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<subsystem_point_pb.State> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/eulynx.point.SubsystemPoint/ConnectWeb',
      request,
      metadata || {},
      this.methodDescriptorConnectWeb);
  }

  methodDescriptorMovePoint = new grpcWeb.MethodDescriptor(
    '/eulynx.point.SubsystemPoint/MovePoint',
    grpcWeb.MethodType.UNARY,
    subsystem_point_pb.Input,
    subsystem_point_pb.Nothing,
    (request: subsystem_point_pb.Input) => {
      return request.serializeBinary();
    },
    subsystem_point_pb.Nothing.deserializeBinary
  );

  movePoint(
    request: subsystem_point_pb.Input,
    metadata: grpcWeb.Metadata | null): Promise<subsystem_point_pb.Nothing>;

  movePoint(
    request: subsystem_point_pb.Input,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: subsystem_point_pb.Nothing) => void): grpcWeb.ClientReadableStream<subsystem_point_pb.Nothing>;

  movePoint(
    request: subsystem_point_pb.Input,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: subsystem_point_pb.Nothing) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/eulynx.point.SubsystemPoint/MovePoint',
        request,
        metadata || {},
        this.methodDescriptorMovePoint,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/eulynx.point.SubsystemPoint/MovePoint',
    request,
    metadata || {},
    this.methodDescriptorMovePoint);
  }

}

