name: Generated Files Consistency

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Generate Baseline 4 Release 2
        working-directory: EulynxBaseline4Release2
        run: |
            make clean
            make

      - name: Generate Baseline 4 Release 3
        working-directory: EulynxBaseline4Release3
        run: |
            make clean
            make

      - name: Assert working directory clean
        run: git diff --exit-code
